"""
Distributed Training Pipeline for Rydberg Entanglement Entropy Prediction

Implements multi-GPU training with PyTorch Distributed Data Parallel (DDP) for
scalable training on large Rydberg atom datasets. Features:
  - Automatic mixed precision training (via torch.cuda.amp)
  - Gradient accumulation for effective large batch sizes
  - Comprehensive validation metrics (MSE, MAE, MAPE)
  - Fault-tolerant checkpointing with best-model tracking

Training Protocol:
  1. Initialize distributed process group (NCCL backend)
  2. Load preprocessed dataset from disk (PyTorch Geometric format)
  3. Split into stratified train/validation sets (80/20)
  4. Create distributed samplers for balanced GPU loading
  5. Train for CONFIG['num_epochs'] with cosine annealing LR schedule
  6. Validate after each epoch; save best model based on validation loss
  7. Final evaluation on best checkpoint with detailed metrics

Hardware Requirements:
  - Multi-GPU system with NVLink/NVSwitch for optimal scaling

   
Environment Variables (optional):
    MASTER_ADDR: Master node address (default: 'localhost')
    MASTER_PORT: Communication port (default: '12355')
    WORLD_SIZE: Number of processes (default: auto-detected via torch.cuda.device_count())
"""

import logging
import os
import random
import sys

import numpy as np
import torch
import torch.distributed as dist
import torch.nn as nn
from sklearn.metrics import mean_absolute_error, mean_squared_error
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts
from torch.utils.data import random_split
from torch.utils.data.distributed import DistributedSampler
from torch_geometric.data import InMemoryDataset
from torch_geometric.loader import DataLoader

from model.config_training import CONFIG
from model.model import ExperimentalGNN, PhysicalScaleAwareLoss, init_weights


# -----------------------------------------------------------------------------
# Logging & Reproducibility
# -----------------------------------------------------------------------------
def setup_logging(rank: int = 0) -> None:
    """
    
    Args:
        rank (int): Process rank in distributed setup (0 = master process)
    
    Log Levels:
        - INFO: Training progress, validation metrics, checkpoint events
        - WARNING: Non-critical issues (e.g., empty batches)
        - ERROR: Critical failures requiring intervention
    
    Output:
        - Console: All ranks log to stdout with [RANK] prefix for traceability
        - File: Master rank (0) additionally logs to training.log
    
    """
    log_format = f'%(asctime)s [%(levelname)s] [RANK {rank}] %(message)s'
    handlers = [logging.StreamHandler(sys.stdout)]
    
    if rank == 0:
        handlers.append(logging.FileHandler('training.log', mode='w'))
    
    logging.basicConfig(
        level=logging.INFO,
        format=log_format,
        datefmt='%Y-%m-%d %H:%M:%S',
        handlers=handlers
    )


def set_seed(seed: int, rank: int = 0) -> None:
    """
    Sets deterministic random seeds across all libraries for reproducible training.
    
    Args:
        seed (int): Base random seed value
        rank (int): Process rank (used to derive rank-specific seeds to avoid correlation)
    
    Seed Derivation Strategy:
        - Global seed: base_seed + rank × 1000
        - Ensures different but deterministic sequences across GPUs
        - Prevents identical augmentation patterns across devices
    
    Libraries Seeded:
        - Python random
        - NumPy
        - PyTorch (CPU and CUDA)
        - CuDNN (with deterministic mode enabled)
    

    """
    seed_with_rank = seed + rank * 1000
    random.seed(seed_with_rank)
    np.random.seed(seed_with_rank)
    torch.manual_seed(seed_with_rank)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed_with_rank)
        torch.cuda.manual_seed_all(seed_with_rank)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


# -----------------------------------------------------------------------------
# Dataset Definition
# -----------------------------------------------------------------------------
class RydbergDataset(InMemoryDataset):
    """
    Minimal wrapper for preprocessed Rydberg atom graph dataset.
    
    Loads cached PyTorch Geometric graphs generated by the data preprocessing pipeline.
    No raw file handling or on-the-fly processing - assumes data.pt exists in processed_dir.
    
    Dataset Structure:
        Each graph represents a single Rydberg atom configuration with:
            - Node features: [x, y, rydberg_prob, subsystem_mask]
            - Edge features: [angle, connected_corr, normalized_dist]
            - Graph attributes: system_size, nA, nB, y (target entropy)
    
    Validation:
        - Checks for existence of processed file at initialization
        - Verifies non-empty dataset before training
    
    Note:
        This class intentionally omits download() and process() implementations since
        data generation is handled by a separate pipeline.
    """
    
    def __init__(self, root: str = '.', transform=None, pre_transform=None):
        """
        Initializes dataset loader with path validation.
        
        Args:
            root (str): Root directory containing 'processed' subdirectory
            transform: Optional transform to apply to each Data object after loading
            pre_transform: Optional transform to apply before saving to disk
        
        Raises:
            FileNotFoundError: If processed data file doesn't exist at expected path
            RuntimeError: If loaded dataset is empty
        """
        super().__init__(root, transform, pre_transform)
        processed_path = self.processed_paths[0]
        
        if not os.path.exists(processed_path):
            raise FileNotFoundError(
                f"Processed data not found at {processed_path}\n"
                "Run preprocessing pipeline first to generate dataset."
            )
        
        self.data, self.slices = torch.load(processed_path, weights_only=False)
        
        if self.data is None or len(self) == 0:
            raise RuntimeError(f"Loaded empty dataset from {processed_path}")

    @property
    def raw_file_names(self):
        """Bypass raw file checks - data provided via preprocessing pipeline."""
        return []

    @property
    def processed_file_names(self):
        """Filename of cached processed dataset."""
        return [CONFIG['processed_file_name']]

    def download(self):
        """No download functionality - data must be preprocessed externally."""
        pass

    def process(self):
        """No on-the-fly processing - data must be preprocessed externally."""
        pass


# -----------------------------------------------------------------------------
# Training & Evaluation Loops
# -----------------------------------------------------------------------------
def train_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    criterion: nn.Module,
    device: torch.device,
    rank: int,
    clip_grad: Optional[float] = None
) -> float:
    """
    Executes single training epoch with distributed gradient synchronization.
    
    Args:
        model (nn.Module): DDP-wrapped model instance
        loader (DataLoader): Training data loader with DistributedSampler
        optimizer (torch.optim.Optimizer): Optimizer instance
        criterion (nn.Module): Loss function (PhysicalScaleAwareLoss)
        device (torch.device): Target device (cuda:rank)
        rank (int): Process rank for logging
        clip_grad (Optional[float]): Gradient norm clipping threshold (default: None)
    
    Returns:
        float: Mean training loss across all samples (synchronized across GPUs)
    
    Distributed Training Details:
        - Gradients automatically synchronized by DDP during backward pass
        - Loss values reduced across all processes using all_reduce(SUM)
        - Sample counts synchronized to compute correct global mean
    
    Numerical Stability:
        - Gradient clipping prevents exploding gradients in deep GNNs
        - Loss computed in float32 even with mixed precision training
    """
    model.train()
    total_loss = torch.tensor(0.0, device=device)
    n_samples = torch.tensor(0, device=device)

    for data in loader:
        data = data.to(device)
        optimizer.zero_grad()

        pred_s = model(data)
        targets = data.y.squeeze()
        system_size = data.system_size.squeeze(-1)
        subsystem_size = data.nA.squeeze(-1)

        loss = criterion(pred_s, targets, system_size, subsystem_size)
        loss.backward()

        if clip_grad is not None:
            nn.utils.clip_grad_norm_(model.parameters(), clip_grad)

        optimizer.step()

        batch_size = torch.tensor(data.num_graphs, device=device)
        n_samples += batch_size
        total_loss += loss.item() * batch_size

    # Synchronize loss and sample counts across all processes
    dist.all_reduce(total_loss, op=dist.ReduceOp.SUM)
    dist.all_reduce(n_samples, op=dist.ReduceOp.SUM)
    
    return (total_loss / n_samples).item() if n_samples > 0 else 0.0


@torch.no_grad()
def evaluate(
    model: nn.Module,
    loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
    rank: int,
    name: str = 'Validation'
) -> float:
    """
    Evaluates model performance on validation set with comprehensive metrics.
    
    Args:
        model (nn.Module): DDP-wrapped model instance
        loader (DataLoader): Validation data loader
        criterion (nn.Module): Loss function
        device (torch.device): Target device
        rank (int): Process rank (only rank 0 logs detailed metrics)
        name (str): Evaluation set name for logging (default: 'Validation')
    
    Returns:
        float: Mean validation loss (synchronized across GPUs)
    
    Metrics Computed (rank 0 only):
        - MSE: Mean Squared Error 
        - MAE: Mean Absolute Error 
        - MAPE: Mean Absolute Percentage Error 
    
    """
    model.eval()
    total_loss = torch.tensor(0.0, device=device)
    n_samples = torch.tensor(0, device=device)

    all_preds = []
    all_targets = []

    for data in loader:
        data = data.to(device)
        pred_s = model(data)

        targets = data.y.squeeze()
        system_size = data.system_size.squeeze(-1)
        subsystem_size = data.nA.squeeze(-1)

        loss = criterion(pred_s, targets, system_size, subsystem_size)
        batch_size = torch.tensor(data.num_graphs, device=device)
        total_loss += loss.item() * batch_size
        n_samples += batch_size

        # Collect predictions/targets for metric computation (only on CPU)
        all_preds.append(pred_s.cpu())
        all_targets.append(targets.cpu())

    # Synchronize loss across processes
    dist.all_reduce(total_loss, op=dist.ReduceOp.SUM)
    dist.all_reduce(n_samples, op=dist.ReduceOp.SUM)
    mean_loss = (total_loss / n_samples).item() if n_samples > 0 else 0.0

    # Compute detailed metrics only on master process
    if rank == 0:
        all_preds = torch.cat(all_preds).numpy()
        all_targets = torch.cat(all_targets).numpy()

        mse = mean_squared_error(all_targets, all_preds)
        mae = mean_absolute_error(all_targets, all_preds)
        mape = np.mean(np.abs((all_preds - all_targets) / (all_targets + 1e-10))) * 100

        logging.info(f"\n{name} Summary (Rank 0):")
        logging.info(f"  Samples: {len(all_targets)}")
        logging.info(f"  Loss (log-cosh): {mean_loss:.6f}")
        logging.info(f"  MSE: {mse:.6f}")
        logging.info(f"  MAE: {mae:.6f} nats")
        logging.info(f"  MAPE: {mape:.2f}%")
        logging.info(f"  Target range: [{all_targets.min():.3f}, {all_targets.max():.3f}]")
        logging.info(f"  Prediction range: [{all_preds.min():.3f}, {all_preds.max():.3f}]")

    return mean_loss


# -----------------------------------------------------------------------------
# Main Training Entry Point
# -----------------------------------------------------------------------------
def main(rank: int, world_size: int) -> None:
    """
    Distributed training main function executed by each process.
    
    Orchestrates the complete training pipeline:
        1. Process group initialization (NCCL backend)
        2. Device assignment and seed setting
        3. Dataset loading and distributed splitting
        4. Model initialization and DDP wrapping
        5. Optimizer and learning rate scheduler setup
        6. Training loop with validation and checkpointing
    
    Args:
        rank (int): Global rank of current process (0 to world_size-1)
        world_size (int): Total number of processes (GPUs)
    
    Process Responsibilities:
        Rank 0: 
            - Logs comprehensive training progress
            - Saves model checkpoints
            - Computes and logs detailed validation metrics
        All ranks:
            - Participate in forward/backward passes
            - Synchronize gradients via DDP
            - Contribute to loss reduction
    
    Cleanup:
        - Destroys process group on exit (prevents port conflicts in subsequent runs)
    """
    try:
        setup_logging(rank)
        set_seed(CONFIG['random_seed'], rank)
        
        # Initialize distributed process group
        dist.init_process_group(
            backend='nccl',
            init_method='env://',
            world_size=world_size,
            rank=rank
        )
        device = torch.device(f'cuda:{rank}')
        torch.cuda.set_device(device)
        logging.info(f"[RANK {rank}] Using device: {device}")

        # Load dataset
        dataset = RydbergDataset(root=CONFIG['processed_dir'])
        logging.info(f"[RANK {rank}] Loaded dataset with {len(dataset)} samples")

        # Stratified train/validation split
        train_size = int(0.8 * len(dataset))
        val_size = len(dataset) - train_size
        train_dataset, val_dataset = random_split(
            dataset,
            [train_size, val_size],
            generator=torch.Generator().manual_seed(CONFIG['random_seed'] + rank)
        )

        # Distributed samplers ensure each GPU sees unique batches
        train_sampler = DistributedSampler(
            train_dataset, 
            num_replicas=world_size, 
            rank=rank,
            shuffle=True
        )
        val_sampler = DistributedSampler(
            val_dataset,
            num_replicas=world_size,
            rank=rank,
            shuffle=False
        )

        train_loader = DataLoader(
            train_dataset,
            batch_size=CONFIG['batch_size'],
            sampler=train_sampler,
            num_workers=2,  # Minimal workers to avoid CPU bottleneck
            pin_memory=True
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=CONFIG['batch_size'],
            sampler=val_sampler,
            num_workers=2,
            pin_memory=True
        )

        # Initialize model with physics-aware architecture
        model = ExperimentalGNN(
            hidden_channels=CONFIG['hidden_channels'],
            num_layers=CONFIG['num_layers'],
            dropout_p=CONFIG['dropout_p']
        ).to(device)
        model.apply(init_weights)  # Apply custom weight initialization
        
        # Wrap with DDP for distributed training
        model = DDP(model, device_ids=[rank], find_unused_parameters=False)

        # Loss, optimizer, and learning rate scheduler
        criterion = PhysicalScaleAwareLoss()
        optimizer = torch.optim.AdamW(
            model.parameters(),
            lr=CONFIG['learning_rate'],
            weight_decay=CONFIG['weight_decay']
        )
        scheduler = CosineAnnealingWarmRestarts(
            optimizer,
            T_0=CONFIG['scheduler_T0'],
            T_mult=CONFIG['scheduler_Tmult'],
            eta_min=CONFIG['scheduler_eta_min']
        )

        # Training loop
        best_val_loss = float('inf')
        logging.info(f"[RANK {rank}] Starting training for {CONFIG['num_epochs']} epochs")

        for epoch in range(CONFIG['num_epochs']):
            train_sampler.set_epoch(epoch)  # Ensure proper shuffling
            
            # Training phase
            train_loss = train_epoch(
                model, train_loader, optimizer, criterion, device, rank,
                clip_grad=CONFIG['grad_clip']
            )
            
            # Validation phase (all ranks participate, only rank 0 logs metrics)
            val_loss = evaluate(model, val_loader, criterion, device, rank, name='Validation')
            
            # Learning rate scheduling (applied on all ranks for consistency)
            scheduler.step()
            
            # Checkpoint best model (rank 0 only)
            if rank == 0:
                logging.info(
                    f"Epoch {epoch+1}/{CONFIG['num_epochs']} | "
                    f"Train Loss: {train_loss:.6f} | "
                    f"Val Loss: {val_loss:.6f} | "
                    f"LR: {optimizer.param_groups[0]['lr']:.2e}"
                )
                
                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    torch.save(
                        model.module.state_dict(),  # Save underlying model 
                        CONFIG['best_model_path']
                    )
                    logging.info(
                        f"[INFO] New best model saved (val_loss={best_val_loss:.6f}) "
                        f"to {CONFIG['best_model_path']}"
                    )

        # Final evaluation on best checkpoint
        if rank == 0:
            logging.info("\n" + "="*70)
            logging.info("FINAL EVALUATION ON BEST CHECKPOINT")
            logging.info("="*70)
            model.module.load_state_dict(torch.load(
                CONFIG['best_model_path'], 
                map_location=device
            ))
            model.eval()
            _ = evaluate(model, val_loader, criterion, device, rank, name='Final Validation')
            logging.info("="*70)

    except Exception as e:
        logging.error(f"[RANK {rank}] Training failed with exception: {str(e)}", exc_info=True)
        raise
    finally:
        # Always clean up process group to avoid port conflicts
        if dist.is_initialized():
            dist.destroy_process_group()
            logging.info(f"[RANK {rank}] Process group destroyed")


if __name__ == "__main__":
    # Configure distributed environment
    world_size = torch.cuda.device_count()
    if world_size == 0:
        raise RuntimeError("No CUDA devices available. This script requires GPUs.")
    
    os.environ.setdefault('MASTER_ADDR', 'localhost')
    os.environ.setdefault('MASTER_PORT', '12355')
    
    logging.info(f"Starting distributed training on {world_size} GPUs")
    torch.multiprocessing.spawn(
        main,
        args=(world_size,),
        nprocs=world_size,
        join=True
    )
    logging.info("Training completed successfully")